# Chat GPT method:

# Sources: 
# Using Sentence Transformers: https://sbert.net/docs/sentence_transformer/usage/usage.html 
# Creating the histogram: https://www.geeksforgeeks.org/data-visualization/plotting-histogram-in-python-using-matplotlib/

# You will find that I commented out lines 94-99 and 107-116.
# There reason is that I had chosen a random threshold for my thesis, to reject the confidence scores of classification below this threshold.
# For the thesis my dataset had more than 1800 entries. Meaning even if the majority of the titles were classified to a topic with a score below the threshold, 
# there were still enough examples of topic-title to see how the algorithm performed.
# On GITHUB I am uploading an example dataset with 10 entries. All of the titles are being classified to topics with a confidence score less than 0,35.
# So for the purposes of you being able to see the classifications, that they won't be written off as "Uncertain" I commented out the threshold lines. 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Loading data:
df = pd.read_excel("fake_dataset.xlsx")
titles = df["English_titles"].fillna("").astype(str).tolist()

# Loading SBERT:
model = SentenceTransformer("all-mpnet-base-v2")

# Embedding the thesis titles:
title_embeddings = model.encode(titles, normalize_embeddings=True)

# Topic names for categorization. 
# Generated by ChatGPT. Full chat log is in the appendix of thesis.
labels = [
    "Economics & Business",
    "Computer Science & AI",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Biology & Life Sciences",
    "Chemistry",
    "Physics",
    "Mathematics & Statistics",
    "Medicine & Health",
    "Psychology & Neuroscience",
    "Sociology",
    "Political Science",
    "Law",
    "Education",
    "Environmental Science",
    "Geography & GIS",
    "Humanities",
    "Linguistics",
    "Gender Studies"
]

# Descriptions of topic names (labels) above. 
# Generated by ChatGPT. Full chat log is in the appendix of thesis.
descriptions = [
    "Economics, finance, business, organizational behavior",
    "Computer science, AI, data systems, computational methods",
    "Electrical engineering, electronics, telecommunications, signal processing",
    "Mechanical engineering, manufacturing, robotics, applied mechanics",
    "Civil engineering, infrastructure, construction, urban systems",
    "Biology, life sciences, ecology, evolution",
    "Chemistry, chemical processes, materials science",
    "Physics, theoretical physics, astrophysics, quantum phenomena",
    "Mathematics, statistics, probability, formal modeling",
    "Medicine, clinical sciences, public health, biomedical research",
    "Psychology, cognition, neuroscience, human behavior",
    "Sociology, social structures, inequality, institutions",
    "Political science, governance, policy, international relations",
    "Law, legal systems, regulation",
    "Education, learning sciences, pedagogy",
    "Environmental science, climate change, sustainability",
    "Geography, spatial analysis, GIS, urban systems",
    "Humanities, history, philosophy, cultural studies",
    "Linguistics, language, communication, discourse",
    "Gender studies, identity, diversity, social equality"
]

# Embedding the topic names:
topic_embeddings = model.encode(descriptions, normalize_embeddings=True)

# Calculating cosine similarity between the thesis titles and topic names:
similarity = cosine_similarity(title_embeddings, topic_embeddings)

# Classifing the thesis titles into topic names based on highest similarity score:
best_idx = np.argmax(similarity, axis=1)
best_score = np.max(similarity, axis=1)

# Adding the categorized topic names for every thesis title in the dataset as the column "Research_area":
# Adding the confidence score of the said categorizations in the dataset as the column "Confidence":
df["Research_Area"] = [labels[i] for i in best_idx]
df["Confidence"] = best_score

# Plotting the histogram showing the distribution of the confidence score: 
plt.hist(df["Confidence"], bins=30, edgecolor="black")
#plt.axvline(
#    x=0.35,
#    color="red",
#    linestyle="--",
#    label="Candidate threshold (0.35)"
#)
plt.xlabel("Cosine similarity to best matching topic")
plt.ylabel("Number of titles")
plt.title("Distribution of Classification Confidence Scores")
plt.tight_layout()
plt.savefig("confidence_distribution.png", dpi=300)
plt.show()

# Creating a confidence treshold to reject some classifications:
# I selected it randomly.
#CONFIDENCE_THRESHOLD = 0.35  

# If confidence score is below confidence treshold, classify topic to title as uncertain:
#df["Research_Area"] = np.where(
#    df["Confidence"] < CONFIDENCE_THRESHOLD,
#    "Uncertain",
#    df["Research_Area"]
#)

# Saving output:
df.to_excel("fake_thesis_classified_final.xlsx", index=False)